name: Auto-deploy Blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: get pnpm store dir
        id: get-pnpm-store
        run: |
          echo "pnpm_store_dir=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.get-pnpm-store.outputs.pnpm_store_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: install dependencies and build
        run: |
          pnpm i --frozen-lockfile
          pnpm build

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: page
          git-config-name: LynnSha1ng
          git-config-email: xiawang0441@gmail.com
          commit-message: Blog deployed.
